//
// Created by paco on 01/09/26.
//

#ifndef PACOCOMPILER_LEXER_H
#define PACOCOMPILER_LEXER_H

typedef enum {
    TOKEN_INVALID,
    TOKEN_IDENTIFIER,
    TOKEN_KEYWORD,
    TOKEN_OPERATOR,
    //TOKEN_SIMPLE_OPERATOR,
    //TOKEN_COMPLEX_OPERATOR,
    TOKEN_NUMBER,
    TOKEN_STRING,
    TOKEN_TYPE_COUNT
} TokenType;

static constexpr int ERROR_OFFSET = 1000;

typedef enum {
    LEX_SUCCESS = 0,
    ER_IDK      = ERROR_OFFSET,
    ER_NO_INPUT,
    ER_INVALID_CHARACTER,

    ER_NUMBER_MISSING_INTEGER_PART,
    ER_NUMBER_MISSING_DECIMAL_PART,
    ER_NUMBER_MISSING_EXPONENT_PART,
    ER_NUMBER_DECIMAL_ON_EXPONENT,
    ER_NUMBER_MORE_THAN_ONE_DECIMAL_POINT,
    ER_NUMBER_MORE_THAN_ONE_EXPONENT,
    ER_NUMBER_MORE_THAN_ONE_EXPONENT_SIGN,
    ER_NUMBER_INVALID_CHARACTER,

    ER_STRING_LEFT_OPEN,      // ("abc)
    ER_STRING_ALREADY_CLOSED, // ("abc"de)

    ER_OPERATOR_TOO_LONG,
    ER_OPERATOR_INVALID_COMPLEX,
    ER_OPERATOR_INVALID_CHARACTER,

    ER_IDENTIFIER_INVALID_CHARACTER,
    ER_IDENTIFIER_LETTER_AFTER_DIGIT, // (foo123a)

    ERROR_COUNT
} LexerResult;

LexerResult parseLexeme(const char* input, TokenType* token_type);
const char* getTokenTypeName(TokenType token_type);

#endif //PACOCOMPILER_LEXER_H
