//
// Created by paco on 01/09/26.
//

#ifndef PACOCOMPILER_LEXER_H
#define PACOCOMPILER_LEXER_H

typedef enum {
    TOKEN_INVALID,
    TOKEN_IDENTIFIER,
    TOKEN_KEYWORD,
    TOKEN_OPERATOR,
    //TOKEN_SIMPLE_OPERATOR,
    //TOKEN_COMPLEX_OPERATOR,
    TOKEN_NUMBER,
    TOKEN_STRING,
    TOKEN_TYPE_COUNT
} TokenType;

static constexpr int ERROR_OFFSET = 1000;

typedef enum {
    LEX_SUCCESS          = 0,
    ER_IDK               = ERROR_OFFSET,
    ER_NO_INPUT          = 1001,
    ER_INVALID_CHARACTER = 1002,

    ER_NUMBER_MISSING_INTEGER_PART        = 1003,
    ER_NUMBER_MISSING_DECIMAL_PART        = 1004,
    ER_NUMBER_MISSING_EXPONENT_PART       = 1005,
    ER_NUMBER_DECIMAL_ON_EXPONENT         = 1006,
    ER_NUMBER_MORE_THAN_ONE_DECIMAL_POINT = 1007,
    ER_NUMBER_MORE_THAN_ONE_EXPONENT      = 1008,
    ER_NUMBER_MORE_THAN_ONE_EXPONENT_SIGN = 1009,
    ER_NUMBER_INVALID_CHARACTER           = 1010,

    ER_STRING_LEFT_OPEN      = 1011, // ("abc)
    ER_STRING_ALREADY_CLOSED = 1012, // ("abc"de)

    ER_OPERATOR_TOO_LONG          = 1013,
    ER_OPERATOR_INVALID_COMPLEX   = 1014,
    ER_OPERATOR_INVALID_CHARACTER = 1015,

    ER_IDENTIFIER_INVALID_CHARACTER  = 1016,
    ER_IDENTIFIER_LETTER_AFTER_DIGIT = 1017, // (foo123a)

    ERROR_COUNT
} LexerResult;

LexerResult parseLexeme(const char* input, TokenType* token_type);
const char* getTokenTypeName(TokenType token_type);

#endif //PACOCOMPILER_LEXER_H
